export const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE'

export const GET_PALAVRA_REQUEST = 'GET_PALAVRA_REQUEST'
export const GET_PALAVRA_SUCCESS = 'GET_PALAVRA_SUCCESS'
export const GET_PALAVRA__ERROR = 'GET_PALAVRA__ERROR'

export const POST_PALAVRA_REQUEST = 'POST_PALAVRA_REQUEST'
export const POST_PALAVRA_SUCCESS = 'POST_PALAVRA_SUCCESS'
export const POST_PALAVRA__ERROR = 'POST_PALAVRA__ERROR'

export const ADD_LIST_PALAVRAS_VISTAS = 'ADD_LIST_PALAVRAS_VISTAS'
export const CHANGE_PALAVRA_DIGITADA = 'CHANGE_PALAVRA_DIGITADA'

export const T = 'T'